name: MC-SkyForge
version: '${project.version}'
main: com.draconincdomain.skyforge.SkyForge
api-version: '1.21'
commands:
  editor:
    description: "example for this"
    usage: "/editor"
    permission: skyforge.admin